name: sonarqube and docker pileline

on :
  pull_request:
    branches:
      -main
    
  push:
    branches:
      -main
    
  workflow_dispatch:

jobs: 
  sonarqube:
    runs-on: self-hosted
    steps :
      - name : chekout code
        uses: actions/checkout@v4

      - name : sonar run
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.projectKey=assignment-4 \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  docker:
    runs-on: [self-hosted, wsl-ubuntu]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

        

        
