name: sonar run
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sonarqube:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: sonar run
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          args: >
            -Dsonar.projectKey=assignment-4
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  push:
    if: ${{ github.event_name == 'push' }}
    runs-on: self-hosted
    environment:
      name: approval
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build and push docker image
        uses: ./.github/actions/docker-build-push
        with:
          image-name: jeevasabari/assignment-4
          tag: ${{ github.sha }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
